### ISSUE TITLE
Error when running sudo checkinstall 

### ISSUE THREAD

**Issue by nsshub** [F1ash/dnscrypt-proxy-gui#17]
I follow instruction to compile from this link. https://askubuntu.com/questions/1003678/install-dnscrypt-proxy-gui
when I reach the next command which is sudo checkinstall, I got error from terminal such bellow :

`_========================= Installation results ===========================
[ 62%] Built target DNSCryptClient
[ 63%] actions for pro.russianfedora.dnscryptclient
[ 65%] Built target pro.russianfedora.dnscryptclient.policy-customtarget
[ 75%] Built target dnscrypt_client_helper
[ 76%] actions for pro.russianfedora.dnscryptclienttest
[ 77%] Built target pro.russianfedora.dnscryptclienttest.policy-customtarget
[ 79%] Building CXX object src/helpers/test_helper/CMakeFiles/dnscrypt_client_test_helper.dir/dnscrypt_client_test_helper.cpp.o
/home/nss/dnscrypt-proxy-gui/src/helpers/test_helper/dnscrypt_client_test_helper.cpp: In function ‘bool preparedConfig()’:
/home/nss/dnscrypt-proxy-gui/src/helpers/test_helper/dnscrypt_client_test_helper.cpp:131:52: error: ‘KeepEmptyParts’ is not a member of ‘Qt’
  131 |             QStringList _parts = _s.split(" ", Qt::KeepEmptyParts);
      |                                                    ^~~~~~~~~~~~~~
/home/nss/dnscrypt-proxy-gui/src/helpers/test_helper/dnscrypt_client_test_helper.cpp: In function ‘bool preparedServiceUnit()’:
/home/nss/dnscrypt-proxy-gui/src/helpers/test_helper/dnscrypt_client_test_helper.cpp:168:52: error: ‘KeepEmptyParts’ is not a member of ‘Qt’
  168 |             QStringList _parts = _s.split("=", Qt::KeepEmptyParts);
      |                                                    ^~~~~~~~~~~~~~
make[2]: *** [src/helpers/test_helper/CMakeFiles/dnscrypt_client_test_helper.dir/build.make:84: src/helpers/test_helper/CMakeFiles/dnscrypt_client_test_helper.dir/dnscrypt_client_test_helper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:372: src/helpers/test_helper/CMakeFiles/dnscrypt_client_test_helper.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

****  Installation failed. Aborting package creation._

Restoring overwritten files from backup...OK

Cleaning up...OK

Bye.
`

by the way I have installed dependencies exactly like the instruction said.

Can you help me to solve this problem ?

![image](https://user-images.githubusercontent.com/20895285/117633065-de2bcf80-b1a7-11eb-9aed-28193da512ad.png)

**Comment by F1ash** [comment]
It related with Qt version... you have version older than 5.14
Looks https://doc.qt.io/qt-5/qt.html#SplitBehaviorFlags-enum

**Comment by jacopotediosi** [comment]
To make it works on Ubuntu 20.04 LTS without upgrade Qt to 5.14:
`rm -rf src/helpers/test_helper/` and remove `add_subdirectory(test_helper)` from `src/helpers/CMakeLists.txt` before `sudo cmake ./`
